### ISSUE TITLE
Shift weekly average line by half a week

### ISSUE THREAD

**Issue by wjchulme** [opensafely/tpp-database-history#63]
The weekly average of recorded events (orange line) is slightly misaligned with the daily count (blue line). This is because the weekly average is put on the horizontal axis at the start of the week, not the middle.

Ideally the date values should be shifted by +3.5 days (or +3 or +4).

**Comment by iaindillingham** [comment]
Resampling is such a pain.

Here, the rule is `W`, which defaults to `W-SUN`, and the label is `left`. So, each orange vertex marks the mean event count for the week following a Sunday. We can see that more clearly if we look at [the appointment chart][1], as a vertex falls on 2023-04-09, which was Easter Sunday.

I think you're okay with the rule, but not okay with the label. I think you'd prefer the label to be Wednesday, meaning that an orange vertex would mark the mean event count for the three days before the Wednesday, the Wednesday, and the three days after the Wednesday. Alas, Pandas only accepts `left` and `right` as the label, no more, so an addition would be necessary.

If that's correct, I think it's important to communicate this decision. Or is it more-or-less accepted that weeks start on Sunday and are best represented by Wednesday?

We could use bars rather than lines: a week bar would be wider than a day bar, after all. But then we'd have bars over-plotting bars. Alternatively, did you consider a seven-day rolling mean, when developing the original notebook?

[1]: https://reports.opensafely.org/reports/opensafely-tpp-database-history/#appointment

**Comment by wjchulme** [comment]
I don't care which day is chosen as the week start. What looks odd is that the weekly average (over days `[x, x+1, ...x+6]`) is plotted on day `x`. It would be better to plot it on day `x+3.5`, because it's then centered on the values over which it is average

**Comment by iaindillingham** [comment]
Thanks, Will. I guess what I'm getting at is that this seems weird to you, but not to me. Or at least, not weird enough to justify adding code to, in effect, modify the `label` argument.

I worked hard to get as much out of the code as possible, as we'll be maintaining it for some time. That centring the weekly mean adds some special-case hackery suggests that I haven't quite modelled the problem correctly.

**Comment by iaindillingham** [comment]
To be sure, `pandas.DateOffset()` and removing the line are candidate solutions. But in both cases, see my comment about special-case hackery.
