### ISSUE TITLE
Improve graph titles

### ISSUE THREAD

**Issue by wjchulme** [opensafely/tpp-database-history#65]
On each graph, the data source is repeated at the top, and the date range is given in small font.

Given the data source is provided as a subheader in the main text, the title on the graph can probably be removed.  Maybe replacing with something like "all events", "since 1 Feb 2020", "last 30 days" would also help readers navigate the graphs? Otherwise they have to read the small font "From 2020-02-01 to 2023-05-01" date range in the subtitle. If nothing else, the font size should be bigger!

**Comment by iaindillingham** [comment]
Possibly, although I think that it helps to have the titles in the charts, should the charts ever be released or saved separately.

The underlying png files are 15" x 7" (300 dpi?) so are larger than they appear in the report. As well as/instead of making the font size bigger, it would be good to click a chart to open it, at full size, in a new tab.
